version: 2
models:
- name: crypto_summary
  description: "Analytics model for crypto data"
  columns:
    - name: volume_traded
      description: "Total amount of crypto traded in that period."
      data_tests:
        - not_null
    - name: trades_count
      description: "Number of trades executed."
      data_tests:
        - not_null
    - name: trading_day
      description: "Date of the trading"
      data_tests:
        - not_null
    - name: asset_pair
      description: "Crypto symbols ETH and BTC"
      data_tests:
        - accepted_values:
              values: ['BINANCE_SPOT_ETH_BTC', 'BINANCE_SPOT_BTC_USDT']
      
